### ISSUE TITLE
I got a problem ;;

### ISSUE THREAD

**Issue by Eli2312** [y2k04/y2k04#1]
Barely ever used github before so I don't know if this is the correct way to reach you or if it's okay to ask about an archived proyect..
I'm trying to install your Doki Doki mod but i get stuck on step 2 
![IMG_20240415_230531](https://github.com/y2k04/y2k04/assets/145735406/1ea22489-8aeb-4187-beb2-1dde9561e4ee)
I don't know wether I downloaded it incorrectly or if it's cause the game is from the epic store, I've never modded anything other than minecraft or the sims before so I don't know how to handle this

**Comment by y2k04** [comment]
This is fine because you aren't able to create issues on archived repos.

The file hash is for the Steam version of the game. I don't have access to the Epic Games version, so I didn't add support for it, nor knew there was a difference between the platforms. I will amend the readme.
